### ISSUE TITLE
Resolves when getting 404 / 505

### ISSUE THREAD

**Issue by runeh** [asset-pipe/asset-pipe-client#15]
Given a call to

```
assetClient
    .createRemoteBundle(manifest.assetIds)
```

If the asset client is configured with a host that exists, but isn't running an asset server then the bundle promise resolves with an error message as a string, rather than reject with something more detailed.

**Comment by trygve-lie** [comment]
This is an generic "unknown" error we have to handle in the client. I guess generating a generic error object with a clear message is fine.

Though; The build server does now return pretty consistent http error objects with detaled info if there is something wrong there. Ex:

```js
{ 
    statusCode: 400,
    error: 'Bad Request',
    message: '"Bundle payload" must be an array' 
}
```

When the build server return an http error object, should we then transform these into proper error objects when we reject the promise? So we keep whats come on the rejection consistent.

**Comment by trygve-lie** [comment]
Fixed initial issue.

**Comment by digitalsadhu** [comment]
Sounds like we can close this. Reopen if I'm wrong.
There are also additional usage errors as of the latest release.
