### ISSUE TITLE
Add reasonable timeouts to requests

### ISSUE THREAD

**Issue by sveisvei** [asset-pipe/asset-pipe-client#16]

**Comment by trygve-lie** [comment]
We pobably want to make this os it possible to pass on an `Agent` to the underlaying http library. Then its possible to fine tune from outside of the client.

**Comment by sveisvei** [comment]
I think we anyhow should have some reasonable default timeout for the operations.

**Comment by digitalsadhu** [comment]
Current release now has timeouts of 5000.
Closing this for now.
